markw: Use keymaster@3.0-impl from Oreo.
Some apps would store their keys via the keystore way.
Since Android P release this isn't sometimes possible
where in Android O it was for this device.

The keystore returns in such cases
W//vendor/bin/hw/android.hardware.keymaster@3.0-service(447): Digest 1 
requested but not supported by KM1 hal
I/keystore(832): -12 1
E/AbstractAESEncryptor(426): java.security.InvalidKeyException: Keystore 
operation failed
...
E/AbstractAESEncryptor(426): Caused by: 
android.security.KeyStoreException: Unsupported digest

This doesn't occur when switching to android.hardware.keymaster@3.0-impl
from Android O stock release.

To not conflict with upstream dependend libraries
* libsoftkeymasterdevice.so
* libkeymaster_messages.so
* libkeymaster_portable.so
* libkeymaster_staging.so
* libsoftkeymaster.so
rename and patch them up so that they only used by this hal.

Change-Id: Icb390056a8799ef7ac3fb294a07955e60eb1668e